### ISSUE TITLE
Consider supporting outputing JSONPatch

### ISSUE THREAD

**Issue by LifeIsStrange** [pjshumphreys/patchmerge#2]
http://jsonpatch.com/

**Comment by pjshumphreys** [comment]
I don't consider rfc6902 in scope for this project. If needed to implement it I would do that as a separate project, but there are probably good parsers for it already which I would probably use instead.

My personal view is that rfc7396 is more immediately obvious to folks that aren't familiar with it, but it doesn't allow array merging, hence this project. I try to avoid domain specific languages such as rfc6902 if I can.

I'd also recommend coupling this project (if you choose to use it) with something that does JSON Schema validation on the merged object in memory before it is persisted, to assert that the changes to be made conform to your own definition of 'valid'.
